import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SanityLive } from "@/sanity/lib/live";
import "../globals.css";
import "../chatkit-override.css";
import { draftMode } from "next/headers";
import Script from "next/script";
// import { VisualEditing } from "next-sanity/visual-editing"; // Temporarily disabled - module not found
import { AppSidebar } from "@/components/app-sidebar";
import { ClientModeToggle } from "@/components/ClientModeToggle";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { FloatingDock } from "@/components/FloatingDock";
import SidebarToggle from "@/components/SidebarToggle";
import { ThemeProvider } from "@/components/ThemeProvider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AuthRefreshHandler } from "@/components/AuthRefreshHandler";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: undefined,
        variables: {
          colorPrimary: '#7c3aed',
          colorBackground: '#09090b',
          colorInputBackground: 'transparent',
          colorInputText: '#ffffff',
          colorText: '#ffffff',
          colorTextSecondary: '#a1a1aa',
          borderRadius: '0.5rem',
          fontFamily: inter.style.fontFamily,
        },
        elements: {
          // Card & Layout
          card: "bg-black/40 backdrop-blur-md border border-white/5 shadow-2xl rounded-2xl",
          rootBox: "clerk-root-box",
          navbar: "hidden", // Hide sidebar in profile for cleaner look
          navbarMobileMenuRow: "hidden",

          // Headers
          headerTitle: "text-white font-medium tracking-tight",
          headerSubtitle: "text-zinc-400 font-light",

          // Inputs
          formFieldLabel: "text-zinc-400 font-medium text-xs uppercase tracking-wider mb-1.5",
          formFieldInput: "bg-white/5 border border-white/10 text-white transition-all focus:border-white/20 focus:bg-white/10 hover:bg-white/10 outline-none shadow-none focus:shadow-none placeholder:text-zinc-600 rounded-lg",

          // Buttons
          formButtonPrimary: "bg-white text-black hover:bg-zinc-200 transition-all font-medium rounded-lg shadow-none",
          socialButtonsBlockButton: "bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-lg transition-all",
          socialButtonsBlockButtonText: "font-normal text-zinc-300",

          // Links & Footer
          footerActionLink: "text-white hover:text-zinc-300 font-normal underline-offset-4",
          footer: "hidden", // Hide default clerk footer for cleaner look

          // Profile specific
          identityPreviewText: "text-white font-medium",
          identityPreviewEditButton: "text-zinc-400 hover:text-white transition-colors",

          // Alerts/Badges
          alert: "bg-white/5 border border-white/10 text-zinc-300",
          badge: "bg-white/10 text-white border border-white/10",
        },
        layout: {
          socialButtonsPlacement: 'bottom',
          logoPlacement: 'none', // Cleaner without logo
        },
      }}
      signInFallbackRedirectUrl="/"
      signUpFallbackRedirectUrl="/"
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            forcedTheme="dark"
            enableSystem={false}
            disableTransitionOnChange
          >
            <Script
              src="https://cdn.platform.openai.com/deployments/chatkit/chatkit.js"
              strategy="afterInteractive"
            />

            <SidebarProvider defaultOpen={false}>
              {/* Handler para detectar callback de SSO y forzar refresh */}
              <Suspense fallback={null}>
                <AuthRefreshHandler />
              </Suspense>

              <SidebarInset className="">{children}</SidebarInset>

              <AppSidebar side="right" />

              <FloatingDock />
              <SidebarToggle />

              {/* Mode Toggle - Disabled: Always dark mode */}
              {/* <div className="fixed md:bottom-6 md:right-24 top-4 right-18 md:top-auto md:left-auto z-20">
                <div className="w-10 h-10 md:w-12 md:h-12">
                  <ClientModeToggle />
                </div>
              </div> */}
            </SidebarProvider>

            {/* Live content API */}
            <SanityLive />

            {(await draftMode()).isEnabled && (
              <>
                {/* <VisualEditing /> */}
                <DisableDraftMode />
              </>
            )}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
